apiVersion : apps/v1
kind: Deployment
metadata:
  name: saadwebdockerfilev2 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saadwebdockerfilev2
  template:
    metadata:
      labels:
        app: saadwebdockerfilev2 
    spec:
      containers:
        - name: saadwebdockerfilev2 
          image: azureregistrydevops.azurecr.io/saadwebdockerfilev2
          ports:
          - containerPort: 80